// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPRTB9tVPENfTuysTg2ZLt2DHU0tVo6IE',
    appId: '1:1091097233790:web:20e3c96afc58dbc41d0b2f',
    messagingSenderId: '1091097233790',
    projectId: 'stylish-e-commerce-app',
    authDomain: 'stylish-e-commerce-app.firebaseapp.com',
    storageBucket: 'stylish-e-commerce-app.appspot.com',
    measurementId: 'G-T436J36KZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_XYFi8pWzytwsJkwG6T1CeyhnKVqRjnE',
    appId: '1:1091097233790:android:c23d18f1c885baac1d0b2f',
    messagingSenderId: '1091097233790',
    projectId: 'stylish-e-commerce-app',
    storageBucket: 'stylish-e-commerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDClwlAfa1gNWuQbPJ5JAktKl1CCyXRK6U',
    appId: '1:1091097233790:ios:5570ae0f59caa5d91d0b2f',
    messagingSenderId: '1091097233790',
    projectId: 'stylish-e-commerce-app',
    storageBucket: 'stylish-e-commerce-app.appspot.com',
    iosBundleId: 'com.example.stylishEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDClwlAfa1gNWuQbPJ5JAktKl1CCyXRK6U',
    appId: '1:1091097233790:ios:5570ae0f59caa5d91d0b2f',
    messagingSenderId: '1091097233790',
    projectId: 'stylish-e-commerce-app',
    storageBucket: 'stylish-e-commerce-app.appspot.com',
    iosBundleId: 'com.example.stylishEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPRTB9tVPENfTuysTg2ZLt2DHU0tVo6IE',
    appId: '1:1091097233790:web:daa754fdd0cc08141d0b2f',
    messagingSenderId: '1091097233790',
    projectId: 'stylish-e-commerce-app',
    authDomain: 'stylish-e-commerce-app.firebaseapp.com',
    storageBucket: 'stylish-e-commerce-app.appspot.com',
    measurementId: 'G-46MGM1NQC6',
  );
}
